## Role Bindings for api-dev 

# Full access for api-dev-11 = ed7f2ac5-bcc8-45b0-b986-cde6044d1dfe
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-full-access-to-api-dev-11
  namespace: api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-full-access
subjects:
- kind: Group
  namespace: api-dev
  name: ed7f2ac5-bcc8-45b0-b986-cde6044d1dfe

---
# Read access for web-dev-11 = f9bf31f6-7e03-4432-b58c-8e7d300f3f9f
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-read-access-to-web-dev-11
  namespace: api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-read-access
subjects:
- kind: Group
  namespace: api-dev
  name: f9bf31f6-7e03-4432-b58c-8e7d300f3f9f

