kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-full-access
  namespace: web-dev
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-read-access
  namespace: web-dev
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-full-access
  namespace: api-dev
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-read-access
  namespace: api-dev
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]