apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: userprofile
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}