apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  namespace: insurance-dev
  labels:
    deploy: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - image: "registryczp7206.azurecr.io/insurance:1.0"
        imagePullPolicy: Always
        name: insurance
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
          
---
apiVersion: v1
kind: Service
metadata:
  name: insurance
  namespace: insurance-dev
spec:
  type: ClusterIP
  selector:
    app: insurance
  ports:
  - protocol: TCP
    name: insurance-http
    port: 80
    targetPort: 8081
# ---
# apiVersion: v1
# kind: Service
# metadata:
#  name: insurance
#  namespace: "ingress-basic"
# spec:
#  type: ExternalName
#  externalName: insurance.web-dev
#  ports:
#    - port: 80