apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api-dev
spec:
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: "ingress-basic"
spec:
  type: ExternalName
  externalName: poi-service.api-dev
  ports:
    - port: 80