apiVersion: v1
kind: Service
metadata:
  name: tripsapi-service
  namespace: api-dev
spec:
  selector:
    app: trips
  ports:
  - name: trips-http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: trips-https
    port: 443
    protocol: TCP
    targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: tripsapi-service
  namespace: "ingress-basic"
spec:
  type: ExternalName
  externalName: tripsapi-service.api-dev
  ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripsapi-service
  namespace: web-dev
spec:
  type: ExternalName
  externalName: tripsapi-service.api-dev
  ports:
    - port: 80
