apiVersion: v1
kind: Service
metadata:
  name: "tripview-service"
  namespace: "web-dev"
spec:
  ports:
    - port: 80
  type: LoadBalancer
  selector:
    app: "tripview"
---
apiVersion: v1
kind: Service
metadata:
  name: "tripview-service"
  namespace: "ingress-basic"
spec:
  type: ExternalName
  externalName: tripview-service.web-dev
  ports:
    - port: 80


  
