apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api-dev

spec:
  selector:
    app: user-java

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: "ingress-basic"
spec:
  type: ExternalName
  externalName: user-java-service.api-dev
  ports:
    - port: 80