apiVersion: apps/v1
kind: Deployment
metadata:
 name: userprofile-deployment
 namespace: api-dev
 labels:
  app: userprofile
spec:
  replicas: 1
  selector:
   matchLabels:
    app: userprofile
  template:
   metadata:
    labels:
     app: userprofile
   spec:
    containers:
    - name: userprofile
      image: registryczp7206.azurecr.io/tripinsights/userprofile:1.0

      volumeMounts: 
      - name: secrets-store-inline
        mountPath: "/secrets"
        readOnly: true

      ports:
       - containerPort: 80

      env:
       - name: SQL_USER
         valueFrom:
          configMapKeyRef:
           name: oh-configs
           key: SQL_USER
       - name: SQL_SERVER
         valueFrom:
          configMapKeyRef:
           name: oh-configs
           key: SQL_SERVER
       - name: SQL_DBNAME
         valueFrom:
          configMapKeyRef:
           name: oh-configs
           key: SQL_DB

      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kvname
          nodePublishSecretRef:           # Only required when using service principal mode
            name: secrets-store-creds