apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: userprofile
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: "ingress-basic"
spec:
  type: ExternalName
  externalName: userprofile-service.api-dev
  ports:
    - port: 80
